import React from 'react';
import Container from '@material-ui/core/Container'
import Grid from '@material-ui/core/Grid'
import Card from '../components/Card'
const mtg = require('mtgsdk');

export default function Home() {
  const sampleData = [
    {
      name: 'Hollow Dogs',
      cmc: 5,
      colors: [ 'Black' ],
      colorIdentity: [ 'B' ],
      type: 'Creature — Phyrexian Zombie Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Phyrexian', 'Zombie', 'Dog' ],
      set: '7ED',
      setName: 'Seventh Edition',
      number: '141',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=13107&type=card',
      rarity: 'Common',
      mvId: '13107',
      id: 'b7f1e009-fab6-5651-af8d-19aafdfe8b3e'
    },
    {
      name: 'Hollow Dogs',
      cmc: 5,
      colors: [ 'Black' ],
      colorIdentity: [ 'B' ],
      type: 'Creature — Phyrexian Zombie Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Phyrexian', 'Zombie', 'Dog' ],
      set: '9ED',
      setName: 'Ninth Edition',
      number: '139',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=83433&type=card',
      rarity: 'Common',
      mvId: '83433',
      id: '977871c4-e750-5179-a01a-fa51ee166fc5'
    },
    {
      name: 'Blink Dog',
      cmc: 3,
      colors: [ 'White' ],
      colorIdentity: [ 'W' ],
      type: 'Creature — Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Dog' ],
      set: 'AFR',
      setName: 'Adventures in the Forgotten Realms',
      number: '3',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=527290&type=card',
      rarity: 'Uncommon',
      mvId: '527290',
      id: '567a3bb4-1ad0-529f-9e0b-fe882f560c93'
    },
    {
      name: 'Blink Dog',
      cmc: 3,
      colors: [ 'White' ],
      colorIdentity: [ 'W' ],
      type: 'Creature — Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Dog' ],
      set: 'AFR',
      setName: 'Adventures in the Forgotten Realms',
      number: '300',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=530934&type=card',
      rarity: 'Uncommon',
      mvId: '530934',
      id: '196318b1-4d1a-5f41-a024-256e63c89a55'
    },
    {
      name: 'Hollow Dogs',
      cmc: 5,
      colors: [ 'Black' ],
      colorIdentity: [ 'B' ],
      type: 'Creature — Phyrexian Zombie Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Phyrexian', 'Zombie', 'Dog' ],
      set: 'BTD',
      setName: 'Beatdown Box Set',
      number: '28',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=27254&type=card',
      rarity: 'Common',
      mvId: '27254',
      id: 'd7587850-ae32-59f4-a22c-f5860800d2bf'
    },
    {
      name: 'Ruff, Underdog Champ',
      cmc: 4,
      colors: [ 'White' ],
      colorIdentity: [ 'W' ],
      type: 'Legendary Creature — Dog Soldier',
      types: [ 'Creature' ],
      subtypes: [ 'Dog', 'Soldier' ],
      set: 'CMB1',
      setName: 'Mystery Booster Playtest Cards 2019',
      number: '10',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=476140&type=card',
      rarity: 'Rare',
      mvId: '476140',
      id: '1adb43c5-679b-5a98-b26f-373de010c160'
    },
    {
      name: 'Ruff, Underdog Champ',
      cmc: 4,
      colors: [ 'White' ],
      colorIdentity: [ 'W' ],
      type: 'Legendary Creature — Dog Soldier',
      types: [ 'Creature' ],
      subtypes: [ 'Dog', 'Soldier' ],
      set: 'CMB2',
      setName: 'Mystery Booster Playtest Cards 2021',
      number: '10',
      imageUrl: undefined,
      rarity: 'Rare',
      mvId: undefined,
      id: '64557230-4a91-5f68-b1d8-4711fbcf57ec'
    },
    {
      name: 'Greater Mossdog',
      cmc: 4,
      colors: [ 'Green' ],
      colorIdentity: [ 'G' ],
      type: 'Creature — Plant Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Plant', 'Dog' ],
      set: 'DDJ',
      setName: 'Duel Decks: Izzet vs. Golgari',
      number: '59',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=338472&type=card',
      rarity: 'Common',
      mvId: '338472',
      id: '7e6164b1-b621-56e9-b4ba-c5509ff2edaf'
    },
    {
      name: 'Thrashing Mossdog',
      cmc: 4,
      colors: [ 'Green' ],
      colorIdentity: [ 'G' ],
      type: 'Creature — Plant Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Plant', 'Dog' ],
      set: 'DGM',
      setName: "Dragon's Maze",
      number: '50',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=369020&type=card',
      rarity: 'Common',
      mvId: '369020',
      id: '2ef21462-163f-5d23-8784-3c12045084f7'
    },
    {
      name: 'Greater Mossdog',
      cmc: 4,
      colors: [ 'Green' ],
      colorIdentity: [ 'G' ],
      type: 'Creature — Plant Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Plant', 'Dog' ],
      set: 'FMB1',
      setName: 'Mystery Booster Retail Edition Foils',
      number: '69',
      imageUrl: undefined,
      rarity: 'Common',
      mvId: undefined,
      id: '3c28efc0-3074-5bfe-9282-5d2e941f98e4'
    },
    {
      name: 'Moon-Eating Dog',
      cmc: 4,
      colors: [ 'Blue' ],
      colorIdentity: [ 'U' ],
      type: 'Creature — Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Dog' ],
      set: 'GS1',
      setName: 'Global Series Jiang Yanggu & Mu Yanling',
      number: '10',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=447058&type=card',
      rarity: 'Uncommon',
      mvId: '447058',
      id: 'b6aa1618-7190-5174-91c3-af110542d6c2'
    },
    {
      name: 'Release the Dogs',
      cmc: 4,
      colors: [ 'White' ],
      colorIdentity: [ 'W' ],
      type: 'Sorcery',
      types: [ 'Sorcery' ],
      subtypes: undefined,
      set: 'JMP',
      setName: 'Jumpstart',
      number: '4',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=489171&type=card',
      rarity: 'Uncommon',
      mvId: '489171',
      id: 'dfb02544-b29a-5982-8d20-f295ff76b001'
    },
    {
      name: 'Dogged Pursuit',
      cmc: 4,
      colors: [ 'Black' ],
      colorIdentity: [ 'B' ],
      type: 'Enchantment',
      types: [ 'Enchantment' ],
      subtypes: undefined,
      set: 'KHM',
      setName: 'Kaldheim',
      number: '85',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=503693&type=card',
      rarity: 'Common',
      mvId: '503693',
      id: '913234cf-0a8a-5aa2-9e69-cd73f6196d4e'
    },
    {
      name: 'Alpine Watchdog',
      cmc: 2,
      colors: [ 'White' ],
      colorIdentity: [ 'W' ],
      type: 'Creature — Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Dog' ],
      set: 'M21',
      setName: 'Core Set 2021',
      number: '2',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=485325&type=card',
      rarity: 'Common',
      mvId: '485325',
      id: '3e14f46a-b9a6-518b-9160-f88b40ad409c'
    },
    {
      name: 'Greater Mossdog',
      cmc: 4,
      colors: [ 'Green' ],
      colorIdentity: [ 'G' ],
      type: 'Creature — Plant Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Plant', 'Dog' ],
      set: 'MMA',
      setName: 'Modern Masters',
      number: '146',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=370511&type=card',
      rarity: 'Common',
      mvId: '370511',
      id: '71168119-be35-52d0-a10d-119887c1d6bf'
    },
    {
      name: 'Mossdog',
      cmc: 1,
      colors: [ 'Green' ],
      colorIdentity: [ 'G' ],
      type: 'Creature — Plant Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Plant', 'Dog' ],
      set: 'NEM',
      setName: 'Nemesis',
      number: '106',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=21290&type=card',
      rarity: 'Common',
      mvId: '21290',
      id: '4b794aaf-515a-51e4-8420-030d0a447669'
    },
    {
      name: 'Mortis Dogs',
      cmc: 4,
      colors: [ 'Black' ],
      colorIdentity: [ 'B' ],
      type: 'Creature — Phyrexian Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Phyrexian', 'Dog' ],
      set: 'NPH',
      setName: 'New Phyrexia',
      number: '66',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=233072&type=card',
      rarity: 'Common',
      mvId: '233072',
      id: 'f863a2d2-46eb-540d-87ec-efbd07395a8b'
    },
    {
      name: 'Dogged Hunter',
      cmc: 3,
      colors: [ 'White' ],
      colorIdentity: [ 'W' ],
      type: 'Creature — Human Nomad',
      types: [ 'Creature' ],
      subtypes: [ 'Human', 'Nomad' ],
      set: 'ODY',
      setName: 'Odyssey',
      number: '20',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=31789&type=card',
      rarity: 'Rare',
      mvId: '31789',
      id: 'ac41b326-f87d-5832-a205-677ea3bb1614'
    },
    {
      name: 'Mad Dog',
      cmc: 2,
      colors: [ 'Red' ],
      colorIdentity: [ 'R' ],
      type: 'Creature — Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Dog' ],
      set: 'ODY',
      setName: 'Odyssey',
      number: '202',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=31818&type=card',
      rarity: 'Common',
      mvId: '31818',
      id: 'b1c3bb94-6c09-534f-b688-c95a1eb2de13'
    },
    {
      name: 'Moon-Eating Dog',
      cmc: 4,
      colors: [ 'Blue' ],
      colorIdentity: [ 'U' ],
      type: 'Creature — Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Dog' ],
      set: 'PLIST',
      setName: 'The List',
      number: '67',
      imageUrl: undefined,
      rarity: 'Uncommon',
      mvId: undefined,
      id: 'e65abf07-75db-5a80-adc5-22f3a9e60811'
    },
    {
      name: 'Release the Dogs',
      cmc: 4,
      colors: [ 'White' ],
      colorIdentity: [ 'W' ],
      type: 'Sorcery',
      types: [ 'Sorcery' ],
      subtypes: undefined,
      set: 'PLIST',
      setName: 'The List',
      number: '308',
      imageUrl: undefined,
      rarity: 'Uncommon',
      mvId: undefined,
      id: 'f2fc8442-3487-5730-b433-77a09fa692e9'
    },
    {
      name: 'Guard Dogs',
      cmc: 4,
      colors: [ 'White' ],
      colorIdentity: [ 'W' ],
      type: 'Creature — Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Dog' ],
      set: 'PLS',
      setName: 'Planeshift',
      number: '5',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=19141&type=card',
      rarity: 'Uncommon',
      mvId: '19141',
      id: '87e89326-a262-587b-9b70-6be118e8583c'
    },
    {
      name: 'Zodiac Dog',
      cmc: 3,
      colors: [ 'Red' ],
      colorIdentity: [ 'R' ],
      type: 'Creature — Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Dog' ],
      set: 'PRM',
      setName: 'Magic Online Promos',
      number: '35102',
      imageUrl: undefined,
      rarity: 'Common',
      mvId: undefined,
      id: 'f31efdc9-b49f-51a5-aff2-be6c7296bb0a'
    },
    {
      name: 'Zodiac Dog',
      cmc: 3,
      colors: [ 'Red' ],
      colorIdentity: [ 'R' ],
      type: 'Creature — Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Dog' ],
      set: 'PTK',
      setName: 'Portal Three Kingdoms',
      number: '130',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=10534&type=card',
      rarity: 'Common',
      mvId: '10534',
      id: '3879e971-4e75-5664-a431-b244dcaa2dfc'
    },
    {
      name: 'Moon-Eating Dog',
      cmc: 4,
      colors: [ 'Blue' ],
      colorIdentity: [ 'U' ],
      type: 'Creature — Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Dog' ],
      set: 'PZ2',
      setName: 'Treasure Chest',
      number: '70823',
      imageUrl: undefined,
      rarity: 'Uncommon',
      mvId: undefined,
      id: '3e466376-b072-5f4c-8ee1-58f48ef58336'
    },
    {
      name: 'Dogpile',
      cmc: 4,
      colors: [ 'Red' ],
      colorIdentity: [ 'R' ],
      type: 'Instant',
      types: [ 'Instant' ],
      subtypes: undefined,
      set: 'RAV',
      setName: 'Ravnica: City of Guilds',
      number: '120',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=87921&type=card',
      rarity: 'Common',
      mvId: '87921',
      id: 'f151a61c-f8b1-5bdd-942d-906796d8ea9a'
    },
    {
      name: 'Greater Mossdog',
      cmc: 4,
      colors: [ 'Green' ],
      colorIdentity: [ 'G' ],
      type: 'Creature — Plant Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Plant', 'Dog' ],
      set: 'RAV',
      setName: 'Ravnica: City of Guilds',
      number: '169',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=87899&type=card',
      rarity: 'Common',
      mvId: '87899',
      id: '90b5c97e-63c5-5e98-b8c6-78e95e23ef68'
    },
    {
      name: 'Resolute Watchdog',
      cmc: 1,
      colors: [ 'White' ],
      colorIdentity: [ 'W' ],
      type: 'Creature — Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Dog' ],
      set: 'RNA',
      setName: 'Ravnica Allegiance',
      number: '19',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=457163&type=card',
      rarity: 'Uncommon',
      mvId: '457163',
      id: 'c2f125ec-847c-501a-8974-59edd31b696d'
    },
    {
      name: 'Hollow Dogs',
      cmc: 5,
      colors: [ 'Black' ],
      colorIdentity: [ 'B' ],
      type: 'Creature — Phyrexian Zombie Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Phyrexian', 'Zombie', 'Dog' ],
      set: 'S99',
      setName: 'Starter 1999',
      number: '81',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=20385&type=card',
      rarity: 'Common',
      mvId: '20385',
      id: '77d59cbe-0293-558a-9552-71e70d098147'
    },
    {
      name: 'Watchdog',
      cmc: 3,
      colors: undefined,
      colorIdentity: undefined,
      type: 'Artifact Creature — Dog',
      types: [ 'Artifact', 'Creature' ],
      subtypes: [ 'Dog' ],
      set: 'TMP',
      setName: 'Tempest',
      number: '314',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=4634&type=card',
      rarity: 'Uncommon',
      mvId: '4634',
      id: '8b7bbdfb-3b99-54b4-b3a9-3a09272d4150'
    },
    {
      name: 'Plague Dogs',
      cmc: 5,
      colors: [ 'Black' ],
      colorIdentity: [ 'B' ],
      type: 'Creature — Phyrexian Zombie Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Phyrexian', 'Zombie', 'Dog' ],
      set: 'UDS',
      setName: "Urza's Destiny",
      number: '66',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=15180&type=card',
      rarity: 'Uncommon',
      mvId: '15180',
      id: 'ffd0eb74-20c8-50b8-9256-3a4858c3d652'
    },
    {
      name: 'Hollow Dogs',
      cmc: 5,
      colors: [ 'Black' ],
      colorIdentity: [ 'B' ],
      type: 'Creature — Phyrexian Zombie Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Phyrexian', 'Zombie', 'Dog' ],
      set: 'USG',
      setName: "Urza's Saga",
      number: '137',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=5606&type=card',
      rarity: 'Common',
      mvId: '5606',
      id: 'bc683913-87d1-5c4b-bb47-fa8c090fd65f'
    },
    {
      name: 'Wild Dogs',
      cmc: 1,
      colors: [ 'Green' ],
      colorIdentity: [ 'G' ],
      type: 'Creature — Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Dog' ],
      set: 'USG',
      setName: "Urza's Saga",
      number: '284',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=8826&type=card',
      rarity: 'Common',
      mvId: '8826',
      id: 'ce47414f-fd26-53a2-ab66-275606f77584'
    },
    {
      name: 'Dogsnail Engine',
      cmc: 0,
      colors: undefined,
      colorIdentity: undefined,
      type: 'Artifact — Contraption',
      types: [ 'Artifact' ],
      subtypes: [ 'Contraption' ],
      set: 'UST',
      setName: 'Unstable',
      number: '178',
      imageUrl: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=439567&type=card',
      rarity: 'Uncommon',
      mvId: '439567',
      id: '6c743c36-1d66-5898-87ce-d32a1e9594c5'
    },
    {
      name: 'Wild Dogs',
      cmc: 1,
      colors: [ 'Green' ],
      colorIdentity: [ 'G' ],
      type: 'Creature — Dog',
      types: [ 'Creature' ],
      subtypes: [ 'Dog' ],
      set: 'WC99',
      setName: 'World Championship Decks 1999',
      number: 'ml284',
      imageUrl: undefined,
      rarity: 'Common',
      mvId: undefined,
      id: '6130e2a5-76e0-523f-a087-32bd4bede970'
    }
  ];  
  // let sampleData = [];
  // mtg.card.where({name: 'Dog'})
  // .then( card => {
  // const sampleData = card.map((card) => ({
  //   name: card.name,
  //   cmc: card.cmc,
  //   colors: card.colors,
  //   colorIdentity: card.colorIdentity,
  //   type: card.type,
  //   types: card.types,
  //   subtypes: card.subtypes,
  //   set:card.set,
  //   setName: card.setName,
  //   number:card.number,
  //   imageUrl: card.imageUrl,
  //   rarity:card.rarity,
  //   mvId:card.multiverseid,
  //   id:card.id
  //   }))
  // });

return (
      <Container>    
        <Grid container>
          {sampleData.map(card =>(
            <Grid item key={card.id} xs={12} md={4} lg={3}>
              <Card card={card}/>
            </Grid>
          ))}
        </Grid>
      </Container>
    )
}